name       : abcMIDI
version    : 2017.04.19
release    : 3
source     :
    - https://netix.dl.sourceforge.net/project/abc/abcmidi/abcmidi/abcMIDI-2017.04.19.zip : ed5c0e0cffb55a56fcf6cdbe037d819ad7028bc0822983f6988b5f78716447cc
license    : GPL-2.0
component  : multimedia.audio
summary    : a set of command line tools to work with ABC and midi music
description: |
    Abcmidi is a package of programs supporting the ABC Music Notation Format (see http://abcnotation.com ). There are numerous programs included. For example, abc2midi converts an abc file to a MIDI file, midi2abc converts a midi file to an abc file,  abc2abc transposes the music to a different key, yaps creates a Postscript file containing the music notation, midicopy copies a selected portion of a MIDI file, and abcsearch searches an abc file for specific musical patterns.
setup      : |
    rm -rf makefile
    %configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
